### ISSUE TITLE
On Mac tests failing due java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by AndriyKalashnykov** [PacktPublishing/Hands-On-Cloud-Native-Applications-with-Java-and-Quarkus#1]
It's a good idea to run tests on "non-standard" port in provided examples with -Dquarkus.http.test-port=8888
mvn install quarkus:dev -Dquarkus.http.test-port=8888

**Comment by janmaterne** [comment]
I use `quarkus.http.test-port=0` hard coded in the `application.properties` so Quarkus chooses a random one. The chosen port is used for `@QuarkusTest`.
